Added LED Toggle
ekiwi/icesugar-chisel pull request #1
Opened 2021-04-23 20:24 UTC by BRF321JOJO

2021-04-23 20:56 UTC, ekiwi requested changes

2021-04-23 20:56 UTC, ekiwi commented on src/chisel/lib/uart/Uart.scala
> +class LEDInput(frequency: Int, baudRate: Int) extends Module {
Please copy this over to your application file, i.e. `src/design/LEDToggle.scala `.

2021-04-23 20:56 UTC, ekiwi commented on src/chisel/lib/uart/Uart.scala
> +class LEDInput(frequency: Int, baudRate: Int) extends Module {
And restore the old `UartMain`.

2021-04-23 20:56 UTC, ekiwi commented on src/chisel/lib/uart/Uart.scala
> +import fpga.ip.ice40._
This file should not depend on the specific FPGA. It should be a library that can be used by a variety of different FPGAs.

2021-04-23 20:56 UTC, ekiwi commented on src/design/Echo.scala
> +// author: Kevin Laeufer <laeufer@cs.berkeley.edu>
feel free to put your name here

2021-04-23 20:56 UTC, ekiwi commented on src/design/LEDToggle.scala
> +}
Here would be a good place to put your `LEDInput` module.

2021-04-24 00:30 UTC, BRF321JOJO reviewed
Fixed!

2021-04-24 01:10 UTC, ekiwi approved these changes
:ship:

2021-04-24 01:10 UTC, merged